### PR TITLE
Support multiple selectors on the same element

### PR DESCRIPTION
**Pull request by estrattonbailey**
Just had another look locally and I think this should be good to go, provided the lack of IE support is OK. Totally up to you!

### CODE REVIEW

**Comment by estrattonbailey** [comment]
Hey yeah, maybe not. Did find [this](https://www.npmjs.com/package/regexp-polyfill), but haven't tested.

Off the top of my head rn this could also be done [like this](https://repl.it/@estrattonbailey/choozy). Could that be done more succinctly, do you think?

**Comment by mikehwagz** [comment]
@estrattonbailey somehow i never noticed you made this PR! whoops... sorry about that.

I dig what you've got going on [here](https://repl.it/@estrattonbailey/choozy) since it avoids using flags. down to update your PR with this approach? no rush of course 🙏

**Comment by mikehwagz** [comment]
i just tested the regexp in your PR in IE11 and it actually works? see last 2 lines of screenshot below:



so let's go with which ever solution leads to a smaller bundle size

**Comment by estrattonbailey** [comment]
Oh wow, ha, forgot about this entirely. Yeah maybe the constructor syntax is OK, but the [inline syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) isn't?

I'll leave it up to you. I don't remember what I was going to use this for, so if you want to scrap this PR that's cool too. 

Another suggestion that might make it smaller: just return everything as an array. Then the ergonomics are the same for single elements or collections as well. Though idk maybe that's confusing 🤔

**Comment by mikehwagz** [comment]
I think I'm going to think about this a bit more before merging or closing... I don't absolutely need this feature as of now, but would be happy to merge it in if anyone ever really really wants it! Anyway, thanks for the PR and feedback :)

**Comment by estrattonbailey** [comment]
Good take, sounds good!

**Pull request closed without merging**
